<a href="https://colab.research.google.com/github/Nquyen264-2005/TH_DEEPLEARNING/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# Tạo thử một mảng đơn giản
arr = np.array([1, 2, 3])
print("Phiên bản Numpy:", np.__version__)
print("Mảng vừa tạo:", arr)

Phiên bản Numpy: 2.0.2
Mảng vừa tạo: [1 2 3]


array 1 chieu

In [8]:
import numpy as np

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


array 2 chieu

In [9]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


Array 3 chieu

In [10]:
d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


Tao array voi gia tri ban dau la 0 hoac 1

In [11]:
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix\n',f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape thay doi kich thuoc ma tran

In [13]:
import numpy as np

# Tạo mảng 2 chiều e
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

# Thay đổi hình dạng mảng e thành (3, 2)
f = e.reshape(3, 2)
print(f)

# Tạo mảng 3 chiều g
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print(g)
print(g.shape)

# Các ví dụ về reshape mảng g
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


Platten la chuyen array nhieu chieu ve 1 chieu

In [14]:
import numpy as np

# Tạo mảng 2 chiều e và làm phẳng
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

# Tạo mảng 3 chiều g và làm phẳng
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Them dong du lieu voi hstack va vstack

In [15]:
f=np.array([1., 2., 3.])
g=np.array([4., 5., 6.])
h_stack=np.hstack((f,g))
print('Horizontal Append\n', h_stack)
v_stack =np.vstack((f,g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


Sinh mang so nguyen ngau nhien

In [17]:
a=np.random.randint(100, size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100, size=(3,4))
print('Random D-D array\n',b)
c=np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [41 94 76 91 58]
Random D-D array
 [[32 78 99 95]
 [68 22  8 47]
 [65 80 58 46]]
Random 3-D array
 [[[16 34 37]
  [27 35 17]
  [50 53 56]
  [45 69 63]]

 [[85 27 34]
  [30  5 73]
  [17 62 81]
  [80 40 38]]

 [[62 76 76]
  [ 9 83 60]
  [ 7 29 96]
  [37  3 39]]]


Sinh mang so thuc trong khoang [0,1]

In [18]:
#sinh ngau nhien mang so thuc [0,1]
a=np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.68926676 0.09710099 0.13395007 0.63089517 0.86242586]
Random 2-D array
 [[0.94263562 0.08349705 0.31402825 0.85804299]
 [0.51203707 0.76388461 0.22144401 0.03771061]
 [0.35427246 0.22837428 0.55962888 0.96830612]]
Random 3-D array
 [[[0.68791513 0.27579353 0.32646319]
  [0.42184793 0.72816131 0.4251669 ]
  [0.53327625 0.83612638 0.15125473]
  [0.74886645 0.35350294 0.12731287]]

 [[0.69203172 0.21622117 0.06040304]
  [0.95198457 0.20375701 0.27268419]
  [0.79805824 0.51510146 0.83688883]
  [0.21896366 0.53839596 0.6440024 ]]

 [[0.15259262 0.69677431 0.70934045]
  [0.39973188 0.48743745 0.37013729]
  [0.57905074 0.45684898 0.23193069]
  [0.08622997 0.35877062 0.90625039]]]


Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [19]:
a=np.random.normal(5, 0.5, 10)
print(a)

[5.34958602 5.67874495 5.20765621 5.56737192 5.7065495  4.66267626
 4.40023628 5.05591293 5.5060788  4.71839405]


Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [21]:
#sinh 1 giá trị ngẫu nhiêu từ mảng giá trị cho trước
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
#sinh ma trận 3 x 5 ngẫu nhiên từ mảng giả trị cho trước
b = np.random.choice([2,4,6,8,10,12,14,16,18,20], size =(3,5))
print(b)

8
[[ 2 16  2 16 18]
 [20  4 18  6 20]
 [ 8 12  6 14 20]]
