<a href="https://colab.research.google.com/github/Nquyen264-2005/TH_DEEPLEARNING/blob/main/Pandas%26BaiTap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

In [2]:
import pandas as pd
data = {
    'Tên': ['Quyên', 'Thúy', 'An'],
    'Điểm': [9, 8, 10]
}
df = pd.DataFrame(data)

print("Phiên bản Pandas:", pd.__version__)
print("\nBảng dữ liệu mẫu:")
print(df)

Phiên bản Pandas: 2.2.2

Bảng dữ liệu mẫu:
     Tên  Điểm
0  Quyên     9
1   Thúy     8
2     An    10


Serues là cấu trúc dữ liệu 1 chiều

In [3]:

a=pd.Series([1., 2., 3.,])
print(a)
print('First value:',a[0])
b=pd.Series([1., 2., 3.,], index=['a','b','c'])
print(b)
print('First value:',b['a'])
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


Tạo đối tưởng dataframe

In [4]:
import numpy as np
import pandas as pd
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)
numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


Tạo dataframe mảng 2 chiều có tên cột

In [5]:
import pandas as pd

dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}

df_dic = pd.DataFrame(dic)

print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [6]:
import numpy as np
import pandas as pd

r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

print(df.head())

        so1       so2       so3       so4
0 -0.189384 -0.573785 -0.063317  1.662635
1  1.026292  0.712816 -0.714968 -0.228979
2 -1.341611 -0.283372  0.532720  1.197201
3  1.323036  1.432675  0.421466  0.204851
4  0.393529 -0.455622 -0.653194 -0.201347


In [72]:
import numpy as np
import pandas as pd
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())
print('Chọn cột so1\n', df['so1'])
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  0.432483  1.616809 -1.434312 -1.102746
1  0.334908  0.432001  0.693240  0.697485
2 -0.398383  0.191177 -0.957876  0.413665
3  0.290443 -0.633326 -1.077772 -0.534087
4  1.158563  1.492068  0.872127 -1.279333
Chọn cột so1
 0     0.432483
1     0.334908
2    -0.398383
3     0.290443
4     1.158563
5     1.249083
6     0.559917
7    -0.034671
8     1.500617
9     1.172442
10   -0.532363
11   -0.655651
12    0.632324
13   -0.371451
14   -0.846292
15   -0.113095
16   -0.445418
17    0.040284
18    0.611236
19   -1.122961
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  0.432483  1.616809 -1.434312 -1.102746
1  0.334908  0.432001  0.693240  0.697485
2 -0.398383  0.191177 -0.957876  0.413665
Chọn nhiều cột
          so1       so3
0   0.432483 -1.434312
1   0.334908  0.693240
2  -0.398383 -0.957876
3   0.290443 -1.077772
4   1.158563  0.872127
5   1.249083  1.053637
6   0.559917  0.573750
7  -0.034671  1.130929


Nối nhiều DataFrame

In [8]:
#Nối nhiều DataFrame
df1=pd.DataFrame({'Name':['Join','Smith',
                           'Paul'],
                 'Age':[25, 30,50]},
                 index=[0,1,2])
df2=pd.DataFrame({'Name':['Adam','Smith'],
                  'Age':[26,11]},
                 index=[3,4])
df_concat = pd.concat([df1,df2])
print('Concate two DataFrame\n', df_concat)
#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
#Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))
#Đổi tên cột
df_rename=df_concat.rename(columns={'Name':'Fullname'})
print('Change column name\n', df_rename)

Concate two DataFrame
     Name  Age
0   Join   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   Join   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   Join   25
3   Adam   26
1  Smith   30
2   Paul   50
Change column name
   Fullname  Age
0     Join   25
1    Smith   30
2     Paul   50
3     Adam   26
4    Smith   11


In [15]:
import requests
import os

file_url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv" # This is a common dataset, replace if a different Salary_Data.csv is intended
file_path = '/content/sample_data/Salary_Data.csv' # Assuming this is the correct path

# Ensure the directory exists
os.makedirs(os.path.dirname(file_path), exist_ok=True)

# Download the file
response = requests.get(file_url)
response.raise_for_status() # Raise an exception for HTTP errors

with open(file_path, 'wb') as f:
    f.write(response.content)

print(f"File downloaded successfully to {file_path}")

File downloaded successfully to /content/sample_data/Salary_Data.csv


Bài 1: Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [21]:
import numpy as np

arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3 đã tạo:")
print(arr)

#---
check_all_nonzero = np.all(arr != 0)

print("\n--- Kết quả kiểm tra ---")
if check_all_nonzero:
    print("Tất cả các phần tử trong mảng đều khác 0.")
else:
    print("Trong mảng có ít nhất một phần tử bằng 0.")

Mảng ngẫu nhiên 3x3 đã tạo:
[[19  7  7]
 [11  8  1]
 [ 3 20 16]]

--- Kết quả kiểm tra ---
Tất cả các phần tử trong mảng đều khác 0.


 Bài 2: Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [23]:
import numpy as np

arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3 đã tạo:")
print(arr)

check_any_nonzero = np.any(arr != 0)

print("\n--- Kết quả kiểm tra ---")
if check_any_nonzero:
    print("Tồn tại ít nhất một phần tử trong mảng khác 0.")
else:
    print("Tất cả các phần tử trong mảng đều bằng 0.")

Mảng ngẫu nhiên 3x3 đã tạo:
[[15  0  9]
 [11  9 15]
 [16 15 19]]

--- Kết quả kiểm tra ---
Tồn tại ít nhất một phần tử trong mảng khác 0.


Bài 3: Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [29]:
import numpy as np

print("--- So sánh mảng 1 chiều ---")
arr1_1d = np.array([1, 2, 3, 4, 5])
arr2_1d = np.array([5, 2, 8, 1, 3])

print("Mảng 1: ", arr1_1d)
print("Mảng 2: ", arr2_1d)
print("\nArr1 > Arr2:", np.greater(arr1_1d, arr2_1d))
print("Arr1 >= Arr2:", np.greater_equal(arr1_1d, arr2_1d))

print("Arr1 < Arr2:", np.less(arr1_1d, arr2_1d))

print("Arr1 <= Arr2:", np.less_equal(arr1_1d, arr2_1d))

print("\n--- So sánh mảng 2 chiều ---")
arr1_2d = np.array([[10, 20, 30], [40, 50, 60]])
arr2_2d = np.array([[5, 25, 20], [40, 45, 70]])

print("Mảng 1:\n", arr1_2d)
print("Mảng 2:\n", arr2_2d)
print("\nArr1 > Arr2:\n", np.greater(arr1_2d, arr2_2d))
print("Arr1 >= Arr2:\n", np.greater_equal(arr1_2d, arr2_2d))
print("Arr1 < Arr2:\n", np.less(arr1_2d, arr2_2d))
print("Arr1 <= Arr2:\n", np.less_equal(arr1_2d, arr2_2d))

--- So sánh mảng 1 chiều ---
Mảng 1:  [1 2 3 4 5]
Mảng 2:  [5 2 8 1 3]

Arr1 > Arr2: [False False False  True  True]
Arr1 >= Arr2: [False  True False  True  True]
Arr1 < Arr2: [ True False  True False False]
Arr1 <= Arr2: [ True  True  True False False]

--- So sánh mảng 2 chiều ---
Mảng 1:
 [[10 20 30]
 [40 50 60]]
Mảng 2:
 [[ 5 25 20]
 [40 45 70]]

Arr1 > Arr2:
 [[ True False  True]
 [False  True False]]
Arr1 >= Arr2:
 [[ True False  True]
 [ True  True False]]
Arr1 < Arr2:
 [[False  True False]
 [False False  True]]
Arr1 <= Arr2:
 [[False  True False]
 [ True False  True]]


Bài 4: Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [30]:
import numpy as np
ones_array = np.ones(10, dtype=int)
zeros_array = np.zeros(10, dtype=int)
fives_array = np.full(10, 5, dtype=int)
result_array = np.concatenate((ones_array, zeros_array, fives_array))
print("Mảng kết quả:")
print(result_array)
print("Kích thước mảng:", result_array.shape)

Mảng kết quả:
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]
Kích thước mảng: (30,)


Bài 5: Viết chương trình tạo mảng số nguyên chẵn từ [30,70]

In [31]:
import numpy as np
even_numbers_array = np.arange(30, 71, 2)

print("Mảng số nguyên chẵn từ 30 đến 70:")
print(even_numbers_array)

Mảng số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Tạo mảng số nguyên lẻ từ [3,999]

In [34]:
import numpy as np
even_numbers_array=np.arange(3,999,2)
print("Mảng số nguyên lẻ từ 3 đến 999:")
print(even_numbers_array)

Mảng số nguyên lẻ từ 3 đến 999:
[  3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37
  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73
  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109
 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143 145
 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181
 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215 217
 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251 253
 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287 289
 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323 325
 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359 361
 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395 397
 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431 433
 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467 469
 471 473 475 477 47

Bài 6: Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0) (Tìm hiểu hamfidentity của numpy)

In [35]:
import numpy as np
identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Bài 7: Viết chương trình tạo mảng 10 phần từ trong khoảng [15,55]. In ra các giá trị ngoài trừ phần tử đầu và cuối

In [36]:
import numpy as np
random_array = np.random.randint(15, 56, size=10)
print("Mảng gốc:", random_array)
print("Các giá trị ngoại trừ phần tử đầu và cuối:", random_array[1:-1])

Mảng gốc: [16 28 30 36 25 37 25 25 26 35]
Các giá trị ngoại trừ phần tử đầu và cuối: [28 30 36 25 37 25 25 26]


Bài 8: Viết chương trình tạo mảng 20 phần tử trong khonarg [0,20] và đổi dấu những số nằm trong khoảng [9,15]

In [68]:
import numpy as np
random_array = np.random.randint(0, 21, size=20)

print("Mảng gốc:", random_array)
condition = (random_array >= 9) & (random_array <= 15)
random_array[condition] = -random_array[condition]

print("Mảng sau khi đổi dấu:", random_array)

Mảng gốc: [10  5 17 19 17 14  8 11 15  8 11 19 19  0 10  8  3 16  1  2]
Mảng sau khi đổi dấu: [-10   5  17  19  17 -14   8 -11 -15   8 -11  19  19   0 -10   8   3  16
   1   2]


Bài 9: Viết chương trình tạo ma trận 3 x4 và mỗi phần tử có giá trị [10,21]

In [38]:
import numpy as np
random_matrix = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4 với các phần tử trong khoảng [10, 21]:")
print(random_matrix)

Ma trận 3x4 với các phần tử trong khoảng [10, 21]:
[[19 20 16 12]
 [20 16 20 12]
 [14 11 18 20]]


Bài 10: Viết chương trình tạo ma trận 10 x 10 các phần tử ở biên có giá trị 1, các phần tử bên trong có giá trị 0

In [39]:
import numpy as np
matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print("Ma trận 10x10 với các phần tử biên là 1 và phần tử bên trong là 0:")
print(matrix)

Ma trận 10x10 với các phần tử biên là 1 và phần tử bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Bài 11: Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chihs là 1,2,3,4,5. (Tìm hiểu hàm diag của numpy)

In [41]:
import numpy as np
diagonal_elements = np.array([1, 2, 3, 4, 5])
matrix_diag = np.diag(diagonal_elements)

print("Ma trận 5x5 với đường chéo chính 1,2,3,4,5:")
print(matrix_diag)

Ma trận 5x5 với đường chéo chính 1,2,3,4,5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Bài tập Viết chương trình tạo ma trận 4 x 4, các phần tử ở đường chéo chính là 0,1,3,4. (Tìm hiểu hàm diag của numpy)

In [42]:
import numpy as np
diagonal_elements = np.array([0, 1, 3, 4])
matrix_diag = np.diag(diagonal_elements)

print("Ma trận 4x4 với đường chéo chính 0,1,3,4:")
print(matrix_diag)

Ma trận 4x4 với đường chéo chính 0,1,3,4:
[[0 0 0 0]
 [0 1 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Bài 12: Viết chương tình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (Tìm hiểu hàm sum của numpy)

In [43]:
import numpy as np

array_3d = np.random.randint(0, 10, size=(3, 3, 3))

print("Mảng 3x3x3 đã tạo:")
print(array_3d)
sum_axis0 = np.sum(array_3d, axis=0)
print("\nTổng theo trục 0 (ví dụ: tổng các phần tử cùng vị trí qua các 'lớp'):")
print(sum_axis0)
sum_axis1 = np.sum(array_3d, axis=1)
print("\nTổng theo trục 1 (tổng các phần tử theo hàng ngang trong mỗi 'lớp'):")
print(sum_axis1)
sum_axis2 = np.sum(array_3d, axis=2)
print("\nTổng theo trục 2 (tổng các phần tử theo cột dọc trong mỗi 'lớp'):")
print(sum_axis2)

Mảng 3x3x3 đã tạo:
[[[1 2 9]
  [9 8 4]
  [5 7 7]]

 [[3 2 0]
  [4 8 3]
  [6 7 8]]

 [[2 3 6]
  [2 9 2]
  [5 6 0]]]

Tổng theo trục 0 (ví dụ: tổng các phần tử cùng vị trí qua các 'lớp'):
[[ 6  7 15]
 [15 25  9]
 [16 20 15]]

Tổng theo trục 1 (tổng các phần tử theo hàng ngang trong mỗi 'lớp'):
[[15 17 20]
 [13 17 11]
 [ 9 18  8]]

Tổng theo trục 2 (tổng các phần tử theo cột dọc trong mỗi 'lớp'):
[[12 21 19]
 [ 5 15 21]
 [11 13 11]]


Bài 13: Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [44]:
import numpy as np

vector1 = np.random.randint(0, 10, size=10)
vector2 = np.random.randint(0, 10, size=10)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
inner_product = np.dot(vector1, vector2)

print("\nInner product của hai vector:", inner_product)

Vector 1: [7 4 5 0 2 5 7 9 1 5]
Vector 2: [3 8 3 0 9 3 9 3 6 1]

Inner product của hai vector: 202


Bài 14: Tạo ma trận A = 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dogf của ma trận A

In [45]:
import numpy as np
matrix_A = np.random.randint(0, 10, size=(4, 3))
print("Ma trận A 4x3:")
print(matrix_A)
vector_y = np.random.randint(0, 10, size=3)
print("\nVector y 3 phần tử:")
print(vector_y)
matrix_A_plus_y = matrix_A + vector_y
print("\nMa trận A sau khi cộng vector y vào mỗi dòng:")
print(matrix_A_plus_y)

Ma trận A 4x3:
[[4 5 9]
 [2 4 3]
 [4 8 4]
 [2 4 2]]

Vector y 3 phần tử:
[1 1 4]

Ma trận A sau khi cộng vector y vào mỗi dòng:
[[ 5  6 13]
 [ 3  5  7]
 [ 5  9  8]
 [ 3  5  6]]


Bài 15: Viết chương trình Pandass để cộng, trừ, nhân, chia 2 Series:[2,4,6,8,19],[1,3,5,7,10]

In [46]:
import pandas as pd
series1 = pd.Series([2, 4, 6, 8, 19])
series2 = pd.Series([1, 3, 5, 7, 10])
print("Series 1:", series1.to_numpy())
print("Series 2:", series2.to_numpy())
sum_series = series1 + series2
print("\nCộng hai Series:", sum_series.to_numpy())
diff_series = series1 - series2
print("Trừ hai Series:", diff_series.to_numpy())
prod_series = series1 * series2
print("Nhân hai Series:", prod_series.to_numpy())
div_series = series1 / series2
print("Chia hai Series:", div_series.to_numpy())

Series 1: [ 2  4  6  8 19]
Series 2: [ 1  3  5  7 10]

Cộng hai Series: [ 3  7 11 15 29]
Trừ hai Series: [1 1 1 1 9]
Nhân hai Series: [  2  12  30  56 190]
Chia hai Series: [2.         1.33333333 1.2        1.14285714 1.9       ]


Bài 16: Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series :[2,4,6,8,10],[1,3,5,7,10]

In [47]:
import pandas as pd
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
print("Series 1:", series1.to_numpy())
print("Series 2:", series2.to_numpy())
sum_series = series1 + series2
print("\nCộng hai Series:", sum_series.to_numpy())
diff_series = series1 - series2
print("Trừ hai Series:", diff_series.to_numpy())
prod_series = series1 * series2
print("Nhân hai Series:", prod_series.to_numpy())
div_series = series1 / series2
print("Chia hai Series:", div_series.to_numpy())

Series 1: [ 2  4  6  8 10]
Series 2: [ 1  3  5  7 10]

Cộng hai Series: [ 3  7 11 15 20]
Trừ hai Series: [1 1 1 1 0]
Nhân hai Series: [  2  12  30  56 100]
Chia hai Series: [2.         1.33333333 1.2        1.14285714 1.        ]


Bài 17: Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên

In [50]:
import pandas as pd
import numpy as np
data = np.random.randint(0, 101, size=(4, 3))
df_random = pd.DataFrame(data, columns=['Column A', 'Column B', 'Column C'])
print("DataFrame ban đầu:")
print(df_random)
df_sorted = df_random.sort_values(by='Column A')
print("\nDataFrame sau khi sắp xếp theo 'Column A':")
print(df_sorted)

DataFrame ban đầu:
   Column A  Column B  Column C
0         3        18        31
1        79        61        62
2         8        53        22
3        67        23        90

DataFrame sau khi sắp xếp theo 'Column A':
   Column A  Column B  Column C
0         3        18        31
2         8        53        22
3        67        23        90
1        79        61        62


Bài 18: Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex)

In [51]:
import pandas as pd
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series ban đầu:")
print(s)
new_index = ['e', 'd', 'a', 'f', 'c']
s_reindexed = s.reindex(new_index)
print("\nSeries sau khi reindex:")
print(s_reindexed)

Series ban đầu:
a    10
b    20
c    30
d    40
dtype: int64

Series sau khi reindex:
e     NaN
d    40.0
a    10.0
f     NaN
c    30.0
dtype: float64


Bài 19: Viết chương trình Pandas tìm những phần tử trong Series x mà không có trong Series y (Tìm hiểu hàm isin của pandas)

In [52]:
import pandas as pd
x = pd.Series([1, 2, 3, 4, 5, 6, 7])
y = pd.Series([2, 4, 6, 8, 10])

print("Series x:", x.to_numpy())
print("Series y:", y.to_numpy())
elements_not_in_y = x[~x.isin(y)]

print("\nCác phần tử trong Series x mà không có trong Series y:")
print(elements_not_in_y.to_numpy())

Series x: [1 2 3 4 5 6 7]
Series y: [ 2  4  6  8 10]

Các phần tử trong Series x mà không có trong Series y:
[1 3 5 7]


Bài 20: Tìm hiểu phép toán numpy.unionld, numpy.insersectld (hội, giao) và viết chương trình minh họa 2 hàm này trên 2 Series x, y ngẫu nhiên có 20 phần tử

In [53]:
import numpy as np
import pandas as pd
x_raw = np.random.randint(0, 30, size=20)
y_raw = np.random.randint(15, 45, size=20)

x = pd.Series(x_raw.tolist())
y = pd.Series(y_raw.tolist())

print("Series x (20 phần tử ngẫu nhiên):")
print(x.to_numpy())
print("\nSeries y (20 phần tử ngẫu nhiên):")
print(y.to_numpy())
union_xy = np.union1d(x, y)
print("\nHợp (Union) của x và y:")
print(union_xy)

intersect_xy = np.intersect1d(x, y)
print("\nGiao (Intersection) của x và y:")
print(intersect_xy)

Series x (20 phần tử ngẫu nhiên):
[23  9 11 11 14 10 23  9 20  0 19 16 28 21  3 13 16 18 13  7]

Series y (20 phần tử ngẫu nhiên):
[24 31 21 21 17 22 18 39 18 34 38 21 26 42 15 27 27 25 29 42]

Hợp (Union) của x và y:
[ 0  3  7  9 10 11 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 31
 34 38 39 42]

Giao (Intersection) của x và y:
[18 21]


Bài 21: Viết chương trình Pandas thêm series y vào series x theo chiều dọc (vertical), chiều ngang (horizontal) (Tìm hiểu hàm append và concat của pandas)

In [54]:
import pandas as pd
series_x = pd.Series([10, 20, 30], name='X_values')
series_y = pd.Series([40, 50, 60], name='Y_values')

print("Series x:")
print(series_x)
print("\nSeries y:")
print(series_y)
series_vertical_concat = pd.concat([series_x, series_y])
print("\nThêm Series y vào Series x theo chiều dọc (vertical concat):")
print(series_vertical_concat)
series_horizontal_concat = pd.concat([series_x, series_y], axis=1)
print("\nThêm Series y vào Series x theo chiều ngang (horizontal concat):")
print(series_horizontal_concat)

Series x:
0    10
1    20
2    30
Name: X_values, dtype: int64

Series y:
0    40
1    50
2    60
Name: Y_values, dtype: int64

Thêm Series y vào Series x theo chiều dọc (vertical concat):
0    10
1    20
2    30
0    40
1    50
2    60
dtype: int64

Thêm Series y vào Series x theo chiều ngang (horizontal concat):
   X_values  Y_values
0        10        40
1        20        50
2        30        60


Bài 22: Viết chương trình Pandas tạo và hiểu dữ liệu DataFrame sau: exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [55]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

print("--- Dữ liệu DataFrame vừa tạo ---")
print(df)

--- Dữ liệu DataFrame vừa tạo ---
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


Bài 23: Viết chương trình Pandas tạo và hiểu dữ liệu DataFrame sau: exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Cho biết 3 dòng đầu tiên

In [56]:
print("\n3 dòng đầu tiên của DataFrame:")
print(df.head(3))


3 dòng đầu tiên của DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


Bài 24: Viết chương trình Pandas tạo và hiểu dữ liệu DataFrame sau: exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Chọn cột 'nam' và 'score'

In [ ]:
print("\nChọn cột 'name' và 'score':")
print(df[['name', 'score']])

Bài 25: Viết chương trình Pandas tạo và hiểu dữ liệu DataFrame sau: exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Chọn những dòng có attemps>2

In [58]:
print("Chọn những dòng có attemps >2: ")
print(df['attempts']>2)

Chọn những dòng có attemps >2: 
a    False
b     True
c    False
d     True
e    False
f     True
g    False
h    False
i    False
j    False
Name: attempts, dtype: bool


Bài 26: Viết chương trình Pandas tạo và hiểu dữ liệu DataFrame sau: exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Cho biết số dòng, số cột của DataFrame

In [60]:
print("\nSố dòng và số cột của DataFrame:")
print(df.shape)


Số dòng và số cột của DataFrame:
(10, 4)


Bài 27:Viết chương trình Pandas tạo và hiểu dữ liệu DataFrame sau: exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Cho biết những dòng có score là NaN(Tìm hiểu hàm isnull của pandas)

In [62]:
print("\nCho biết những dòng có score là NaN")
print(df[df['score'].isnull()])


Cho biết những dòng có score là NaN
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


Bài 28: Cho biết những dogf có score trong khoảng (15,20) (tìm hiểu hàm between của pandas)

In [63]:
print("\nCác dòng có score trong khoảng (15, 20):")
print(df[df['score'].between(15, 20, inclusive='left')])


Các dòng có score trong khoảng (15, 20):
        name  score  attempts qualify
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes


Bài 29: Cho biết những dòng có attempt >2 và score trong khoảng (15, 20)

In [65]:
print("Chọn những dòng có attemps >2: ")
print(df['attempts']>2)
print("\nCác dòng có score trong khoảng (15, 20):")
print(df[df['score'].between(15, 20, inclusive='left')])
print ("Cho biết những dòng có attempt>2 và score trong khoảng (15,20):")
print(df[(df['attempts'] > 2) & (df['score'].between(15, 20, inclusive='left'))])

Chọn những dòng có attemps >2: 
a    False
b     True
c    False
d     True
e    False
f     True
g    False
h    False
i    False
j    False
Name: attempts, dtype: bool

Các dòng có score trong khoảng (15, 20):
        name  score  attempts qualify
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
Cho biết những dòng có attempt>2 và score trong khoảng (15,20):
Empty DataFrame
Columns: [name, score, attempts, qualify]
Index: []


Bài 30: Cho biết những thay đổi giá trị dòng 'd' , cột score là 19 (tìm hiểu hàm loc của pandas)

In [67]:
print("DataFrame trước khi thay đổi:")
print(df)
df.loc['d', 'score'] = 19

print("\nDataFrame sau khi thay đổi giá trị score của dòng 'd' thành 19:")
print(df)

DataFrame trước khi thay đổi:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

DataFrame sau khi thay đổi giá trị score của dòng 'd' thành 19:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
